### PR TITLE
added token-creator package

### PR DESCRIPTION
**Pull request by Krulknul**

### CODE REVIEW

**Comment by jakerdxworks** [comment]
Hey @Krulknul , is there a reason why you have 2 submissions in this PR? Would prefer to only have one a time. Additionally, it would be great if you could provide a brief explanation of your submission and a way for me to test your submission in a README file :). Thanks kindly for your submission!

**Comment by Krulknul** [comment]
Hello Jake :)I’m sorry if I did it the clumsy way… Of course, I’ll gladly add some more documentation!Should I split the commits into multiple PR’s? Is that even possible?I’m sorry, I’m not so well-versed in git yet.CheersKrulkOn 7 Feb 2023, at 10:47 PM, jakerdxworks ***@***.***> wrote:﻿
Hey @Krulknul , is there a reason why you have 2 submissions in this PR? Would prefer to only have one a time. Additionally, it would be great if you could provide a brief explanation of your submission and a way for me to test your submission in a README file :). Thanks kindly for your submission!

**Comment by Krulknul** [comment]
> Hey @Krulknul , is there a reason why you have 2 submissions in this PR? Would prefer to only have one a time. Additionally, it would be great if you could provide a brief explanation of your submission and a way for me to test your submission in a README file :). Thanks kindly for your submission!

Should I remove one of the submissions from this branch, create a new branch, and push it on there?

**Comment by Krulknul** [comment]
Closing, and opening two seperate pull requests.

**Pull request closed without merging**
